### ISSUE TITLE
Modify tile width and number of tiles

### ISSUE THREAD

**Issue by unrealwill** [victorqribeiro/isocity#10]
Happy new year ! 
Nice work :)
I tried to modified Tilewidth, number of tiles but it doesn't work right.

I modified : 
https://github.com/victorqribeiro/isocity/blob/97dbe43d8dc903e1df5d205c1de9d2a920c21621/js/main.js#L160

to allow tile size modifications, 
`c.drawImage(texture,j,i,130,230,-tileWidth/2-1,-tileHeight*2-2,tileWidth,tileHeight*230 / 66 );`

Display works right but formulas for mouse event needs modification which reveal the logic bug in actual formula.

It probably still require some work to remove the remaining magic numbers and to make it pixel perfect. (There are currently some one pixel width lines between tiles for some tiles). There are probably some dark pixel magic needed to have it render pixel perfect without interpolation issues and texture sampling.

Similarly increase the number of tiles doesn't work.

Also by the way the lighting of the ground of the last tile is inverted with respect to all other tiles.

It looks really nice, well done !

**Comment by victorqribeiro** [comment]
thanks. for now I'm not thinking about creating a larger map.

**Comment by victorqribeiro** [comment]
I had flipped the tile that was inverted
