### ISSUE TITLE
Visual asset has not tidied up

### ISSUE THREAD

**Issue by JerryWaaaaaaaa** [victorqribeiro/isocity#20]
I was playing around with this generator and found that for one of the asset was probably cropped a little off, so there is a red margin at the right bottom corner. 
![Lark20200103-170432](https://user-images.githubusercontent.com/39850796/71715299-ed7c6980-2e4b-11ea-98db-8a35068cbf05.png)

**Comment by victorqribeiro** [comment]
yeah, I noticed it to. I'll try to fix it later

**Comment by victorqribeiro** [comment]
fixed https://github.com/victorqribeiro/isocity/commit/ccb6523289dd5e65a0a3971e72cd2b0dc282d8c7
