### ISSUE TITLE
Better sizing for various screen sizes

### ISSUE THREAD

**Issue by transiient** [victorqribeiro/isocity#23]
On my laptop the screen is taken up mostly by the city with minimal space for tools:

![image](https://user-images.githubusercontent.com/6699307/72203861-49a54600-3469-11ea-925f-e9c31d2d0bec.png)

The board and tools could be scaled to adjust to different screen sizes. Below I'm using `transform: scale();` as an example of the effect, but I wonder if this could be implemented in a better way?

![image](https://user-images.githubusercontent.com/6699307/72203878-a143b180-3469-11ea-9b83-973e974a0dce.png)

I'm willing to work on this if anybody could give tips on scaling the background image itself relative to the size of the board, rather than scaling the entire element itself.

**Comment by victorqribeiro** [comment]
You can always fiddle with the zoom on your browser. Me and most of the user are satisfied with the size of the board. If I ever build a more complex version and would implement zoom, rotation and a bigger board, but for the simplicity of this project I think is fine like it is.
