### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by romettm** [victorqribeiro/isocity#25]
I have been looking isometric map engines and this is really good. I would like to combine different objects on same tile. Could you add feature or tell how to add a feature where tiles would be (vertically) stackable. Eg adding streets lights and trees on same road tile.

Can it be done?

**Comment by victorqribeiro** [comment]
yes, it can be done. You need to check the mouse coordinates to see if there's already a tile blocking the view to the tile the mouse are on and place the tile accordingly
