### ISSUE TITLE
Add the textures source file

### ISSUE THREAD

**Issue by MHM5000** [victorqribeiro/isocity#8]
Hi there!

I believe if you add the source file to this repo, some of us could help with adding more structures like swimming pools, lakes, bridges and more.

**Comment by victorqribeiro** [comment]
https://opengameart.org/content/isometric-city
https://opengameart.org/content/isometric-buildings-1

**Comment by victorqribeiro** [comment]
is there someone working is this? two people on Hackernews expressed the desire to add more tiles

**Comment by MHM5000** [comment]
I haven't started yet.

The current images also need to be reviewed. Not all the side colors
(ground/dirt) are the same.

**Comment by victorqribeiro** [comment]
No one seems to be working on this, closing it for now.
